### PR TITLE
vorpal-setorprint

### PR DESCRIPTION
**Pull request by AljoschaMeyer**
[setorprint](https://github.com/AljoschaMeyer/vorpal-setorprint) - because I am that lazy, and other might be too. Or, I mean, because code reusage is a good thing. Yes, that was the reason.

My nonnativespeakerness allows me to construct words by chaining them, but prevents me from finding a good title for the category. While the other extensions on the list directly add functionality to a program, this one is more of a utility for the coder. [log](https://github.com/AljoschaMeyer/vorpal-log) would go into the same category, once it works with vantage. Or at least into the same set of categories - are those nestable?  
Anyways, I hope you have a good name for this category - even if this extension doesn't qualify as 'awesome', the logging thing will need the category.

### CODE REVIEW

**Comment by dthree** [comment]
Nice :)
1. Rename the category to "Vorpal development tools", and then throw `watch` into it as well and out of the realtime section.
2. I like the idea, but perhaps you should use the term "key / value pair" when describing it. What you're doing is making setter / getter commands in Vorpal really easy. Once I understood that principle, I understood the lib, but it took me a bit to realize that's what it was done.

Yes, it prints the value and you should say that, but maybe consider changing the terminology to make the setter / getter concept more clear? Just a suggestion :)

**Comment by AljoschaMeyer** [comment]
I'll do this once I made the changes to setorprint discussed [here](https://github.com/AljoschaMeyer/vorpal-setorprint/issues/1). No reason to put this on the list, only to break the api one day later.

**Comment by dthree** [comment]
Haha - okay.

**Comment by dthree** [comment]
:+1:

**Pull request merged**
